### ISSUE TITLE
An exception of type 'System.InvalidOperationException' at line number 104 in Form1.cs

### ISSUE THREAD

**Issue by vinaykp9** [lakrsv/EasyQuizTool#2]
I have attached a screen shot of bug . Did you face this issue? any known reasons 

![bug1](https://cloud.githubusercontent.com/assets/6682037/17079794/292c5b4c-5138-11e6-9d0b-2af946638f3e.PNG)

**Comment by lakrsv** [comment]
Hi, sorry, I never saw your message. I can't promise I have time to look at it (If you still have the issue, that is). But the solution should be to call WinForms methods from the master thread. That while loop there is running in a seperate thread, try invoking it from the main thread.

**Comment by lakrsv** [comment]
Fixed :) Sorry it took so long, I didn't actually expect anyone to use this code.
